#!/usr/bin/env python3

# Copyright (c) 2020 , piya.pimchankam@gmail.com
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the Willow Garage, Inc. nor the names of its
#      contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import rospy
from geometry_msgs.msg import Twist
from std_msgs.msg import Bool
from piyabot_msgs.msg import MotorCommand
import Jetson.GPIO as GPIO
import time

LEFT_PWM_PIN = 33
RIGHT_PWM_PIN = 32

LEFT_DIR_PIN = 31
RIGHT_DIR_PIN = 29

MOTOR_POWER_EN_PIN = 22

class PwmControl(object):
    def __init__(self, left_pwm_pin = 33, right_pwm_pin = 32, motor_cmd_topic_name="motor_cmd", motor_power_topic_name="motor_power"):
        # Pin Setup:
        # Board pin-numbering scheme
        GPIO.setmode(GPIO.BOARD)

        self._left_dir_pin = LEFT_DIR_PIN
        self._right_dir_pin = RIGHT_DIR_PIN
        self._power_en_pin = MOTOR_POWER_EN_PIN

        # set pin as an output pin with optional initial state of HIGH
        GPIO.setup(self._left_dir_pin, GPIO.OUT, initial=GPIO.LOW)
        GPIO.setup(self._right_dir_pin, GPIO.OUT, initial=GPIO.LOW)
        GPIO.setup(self._power_en_pin, GPIO.OUT, initial=GPIO.LOW)


        GPIO.setup(left_pwm_pin, GPIO.OUT, initial=GPIO.HIGH)
        self._left_pwm = GPIO.PWM(left_pwm_pin, 50)
        GPIO.setup(right_pwm_pin, GPIO.OUT, initial=GPIO.HIGH)
        self._right_pwm = GPIO.PWM(right_pwm_pin, 50)
        self._left_pwm.start(0)
        self._right_pwm.start(0)
        self._last_left_pwm = 0
        self._last_right_pwm = 0
        self._last_left_dir = False
        self._last_right_dir = False

        self._sub = rospy.Subscriber(motor_cmd_topic_name, MotorCommand, self._cmd_vel_callback ) 
        self._power_sub = rospy.Subscriber(motor_power_topic_name, Bool, self._power_callback ) 


    def set_pwm(self, left_val, right_val):
        self._left_pwm.start(left_val)
        self._right_pwm.start(right_val)

    def _power_callback(self, cmd):
        GPIO.output(self._power_en_pin, cmd.data)

    def _cmd_vel_callback(self, cmd):

        if cmd.left_motor > 100 :
            cmd.left_motor = 100
        if cmd.right_motor > 100 :
            cmd.right_motor = 100

        if cmd.left_motor != self._last_left_pwm :
            self._last_left_pwm = cmd.left_motor
            rospy.loginfo("PWM Left:{}".format(self._last_left_pwm))
            left_dir = False
            lef_pwm = self._last_left_pwm
            if self._last_left_pwm < 0:
                left_dir = True
                lef_pwm = abs(self._last_left_pwm)

            if left_dir != self._last_left_dir :
                self._last_left_dir = left_dir
                self._left_pwm.ChangeDutyCycle(0)
                time.sleep(0.01)     #10 msec
                GPIO.output(self._left_dir_pin, left_dir)
                time.sleep(0.01)     #10 msec

            self._left_pwm.ChangeDutyCycle(lef_pwm)
            

        if cmd.right_motor != self._last_right_pwm :
            self._last_right_pwm = cmd.right_motor
            rospy.loginfo("PWM Right:{}".format(self._last_right_pwm))
            right_dir = False
            right_pwm = self._last_right_pwm

            if self._last_right_pwm  < 0 :
                right_dir = True
                right_pwm = abs(self._last_right_pwm)

            if right_dir != self._last_right_dir :
                self._last_right_dir = right_dir
                self._right_pwm.ChangeDutyCycle(0)
                time.sleep(0.01)     #10 msec
                GPIO.output(self._right_dir_pin, right_dir)
                time.sleep(0.01)     #10 msec

            self._right_pwm.ChangeDutyCycle(right_pwm)
            
        



    def close(self):
        self._left_pwm.stop()
        self._right_pwm.stop()
        GPIO.cleanup()



def listener():

    rospy.init_node('pwm_control', anonymous=True)

    motor_cmd_topic_name = rospy.get_param("motor_cmd_topic_name", "/motor_cmd")

    pwm = PwmControl(LEFT_PWM_PIN, RIGHT_PWM_PIN, motor_cmd_topic_name)
    print("PWM running. Press CTRL+C to exit.")
    # spin() simply keeps python from exiting until this node is stopped
    rospy.spin()

    pwm.close()
    

if __name__ == '__main__':
    listener()


